/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lecarsystem;

import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import static lecarsystem.LeCarSystem.employeeStatus;

import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVParser;
import org.apache.commons.csv.CSVRecord;
/**
 *
 * @author jze20
 */
public class VehiclePage extends javax.swing.JFrame {
    private Function function = new Function();
    private static String[] filePath;
    /**
     * Creates new form VehiclePage
     */
    public VehiclePage() {
        try{
            BufferedReader reader = new BufferedReader(new FileReader("path.txt"));
            String line = reader.readLine();
            filePath = line.split(",");

        }catch (Exception e){
            e.printStackTrace();
        }
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        try{
            BufferedReader reader = new BufferedReader(new FileReader("path.txt"));
            String line = reader.readLine();
            String [] filepath = line.split(",");

            File vehicle_csv = new File(filepath[3]);
            DefaultTableModel vehicle_data = new DefaultTableModel();

            try{
                int start = 0;
                InputStreamReader inputstreamreader = new InputStreamReader(new FileInputStream(vehicle_csv));
                CSVParser csvParser = CSVFormat.DEFAULT.parse(inputstreamreader);

                for(CSVRecord csvRecord:csvParser){
                    if(start == 0){
                        start =1;
                        vehicle_data.addColumn(csvRecord.get(0));
                        vehicle_data.addColumn(csvRecord.get(1));
                        vehicle_data.addColumn(csvRecord.get(2));
                        vehicle_data.addColumn(csvRecord.get(3));
                        vehicle_data.addColumn(csvRecord.get(4));
                    }
                    else
                    {
                        Vector row = new Vector();
                        row.add(csvRecord.get(0));
                        row.add(csvRecord.get(1));
                        row.add(csvRecord.get(2));
                        row.add(csvRecord.get(3));
                        row.add(csvRecord.get(4));
                        vehicle_data.addRow(row);
                    }
                }
            }catch (Exception e){
                System.out.println("Error");
            }
            VehicleTable = new javax.swing.JTable();
            btnAddVehicle = new javax.swing.JButton();
            jLabel1 = new javax.swing.JLabel();
            btnLogout = new javax.swing.JButton();
            txtAccPrice = new javax.swing.JTextField();
            btnSearch = new javax.swing.JButton();
            txtWord = new javax.swing.JTextField();
            txtSalesPrice = new javax.swing.JTextField();
            txtStatus = new javax.swing.JTextField();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            btnImport = new javax.swing.JButton();
            jMenuBar1 = new javax.swing.JMenuBar();
            jMenu1 = new javax.swing.JMenu();
            jMenuItem1 = new javax.swing.JMenuItem();
            jMenuItem2 = new javax.swing.JMenuItem();
            jMenuItem3 = new javax.swing.JMenuItem();
            jMenuItem4 = new javax.swing.JMenuItem();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            VehicleTable.setModel(vehicle_data);
        }catch (Exception e){
            e.printStackTrace();
        }
        jScrollPane1.setViewportView(VehicleTable);

        btnAddVehicle.setText("Add Vehicle");
        btnAddVehicle.setBackground(Color.ORANGE);
        btnAddVehicle.setFont(new Font("Serif",Font.PLAIN,13));
        btnAddVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVehicle(evt);
            }
        });

        jLabel1.setText("Vehicle");
        jLabel1.setFont(new Font("Sans-Serif",Font.BOLD,18));

        btnLogout.setBackground(Color.BLUE);
        btnLogout.setForeground(Color.WHITE);
        btnLogout.setFont(new Font("Serif",Font.PLAIN,13));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search(evt);
            }
        });

        jLabel2.setText("Accquire Price :");

        jLabel3.setText("Status :");

        jLabel4.setText("Sales Price :");

        jLabel5.setText("Word :");

        btnImport.setText("Import");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Import(evt);
            }
        });

        jMenu1.setText("Tables");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem1.setText("Sales");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem2.setText("Customer");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem3.setText("Vehicle");
        jMenu1.add(jMenuItem3);

        if(LeCarSystem.employeeStatus == "1"){
            jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
            jMenuItem4.setText("Employee");
            jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem4ActionPerformed(evt);
                }
            });
            jMenu1.add(jMenuItem4);
        }

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(521, 521, 521)
                        .addComponent(btnLogout))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAddVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImport))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnSearch)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAccPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSalesPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtWord, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLogout)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(txtAccPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalesPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImport))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == jMenuItem1){
            new SalesPages().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == jMenuItem2){
            new CustomerPage().setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void AddVehicle(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVehicle
        // TODO add your handling code here:
        new AddVehicle().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddVehicle

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == jMenuItem4){
            new EmployeePage().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void Logout(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout
        // TODO add your handling code here:
        if (evt.getSource() == btnLogout) 
        {
            int clear = JOptionPane.showConfirmDialog(null, "Logout ?");
            if (clear == JOptionPane.YES_OPTION)
            {  
                JOptionPane.showMessageDialog(null,"Logout Successful");
                employeeStatus = "0";
                new LeCarSystem().setVisible(true);
                this.dispose();
                
            } 
        } 

    }//GEN-LAST:event_Logout

    private void Search(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search
        // TODO add your handling code here:
        if(evt.getSource() == btnSearch){
            String word = txtWord.getText();
            String salesInput = txtSalesPrice.getText();
            String accquireInput = txtAccPrice.getText();
            String carStatus = txtStatus.getText();
            int sales,accquire;
            String status;

            if (salesInput.isEmpty()){ sales = 0;}
            else {sales = Integer.parseInt(salesInput);}
            
            if (accquireInput.isEmpty()){ accquire = 0;}
            else {accquire = Integer.parseInt(accquireInput);}
            
            if (carStatus.isEmpty()){ status = "10";}
            else {status = carStatus;}
            
            try{
                searchfilter(word,sales, accquire,status);
            }catch (Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_Search

    private void Import(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Import
        // TODO add your handling code here:
        if(evt.getSource() == btnImport){
        function.importfunction(3);
        new VehiclePage().setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_Import

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehiclePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehiclePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehiclePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehiclePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehiclePage().setVisible(true);
            }
        });
    }
    
    private void searchfilter(String word,int sales, int accquire, String status) throws Exception{
        File vehicle_csv = new File(filePath[3]);
        DefaultTableModel NEW_VEHICLE = new DefaultTableModel();

        try{
            int start = 0;
            InputStreamReader inputstreamreader = new InputStreamReader(new FileInputStream(vehicle_csv));
            CSVParser csvParser = CSVFormat.DEFAULT.parse(inputstreamreader);


            for(CSVRecord csvRecord:csvParser){
                if(start == 0){
                    start =1;
                    {
                        NEW_VEHICLE.addColumn(csvRecord.get(0));
                        NEW_VEHICLE.addColumn(csvRecord.get(1));
                        NEW_VEHICLE.addColumn(csvRecord.get(2));
                        NEW_VEHICLE.addColumn(csvRecord.get(3));
                        NEW_VEHICLE.addColumn(csvRecord.get(4));
                    }
                }
                else
                {
                    String salesOutput = csvRecord.get(4);
                    int salesValue;
                    
                    if (salesOutput.isEmpty()){ salesValue = 0;}
                    else {salesValue = Integer.parseInt(salesOutput);}               
                     
                    int accquireValue = Integer.parseInt(csvRecord.get(2));
                    
                    if((csvRecord.get(0).contains(word) || csvRecord.get(1).contains(word) 
                            || csvRecord.get(2).contains(word) || csvRecord.get(3).contains(word) 
                            || csvRecord.get(4).contains(word)) && salesValue >= sales && accquireValue >= accquire && status.contains(csvRecord.get(3))){
                        
                        Vector row = new Vector();
                        row.add(csvRecord.get(0));
                        row.add(csvRecord.get(1));
                        row.add(csvRecord.get(2));
                        row.add(csvRecord.get(3));
                        row.add(csvRecord.get(4));
                        NEW_VEHICLE.addRow(row);
                        }
                }
            }
        }catch (Exception e){
                e.printStackTrace();
            }

            VehicleTable.setModel(NEW_VEHICLE);
            jScrollPane1.setViewportView(VehicleTable);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable VehicleTable;
    private javax.swing.JButton btnAddVehicle;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAccPrice;
    private javax.swing.JTextField txtSalesPrice;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtWord;
    // End of variables declaration//GEN-END:variables
}
